### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by maeda-san** [maeda-san/protas#3]
- DB設計
- 正規化
- Qiita:teamで共有

**Comment by maeda-san** [comment]
# Review

## departments

OK!

## users
- 初期バージョンではロール管理は行わない?(全員が全てを編集できる)
- 一人が複数の部署に入る場合もある(ex.飯塚さん)

## clients

OK!

## projects
- プロジェクトID(サロゲートキーでなく)が必要
- 開始日はどのタイミング?(制作の開始日?or見積もり日?or得意先にその案件で初コンタクトをとったとき?)
- 内部納期が必要(Not Null)かどうか(コーディング案件やデザイン案件で内部納期を設定する慣習があるのかよくわからない)
- 窓口担当社員IDは複数持てるようにしたほうが良いかも

## tasks
- 開始日・終了日は予定?また、タスク作成時に確定しなさそうな項目。どういった利用用途を想定?

## man_hours
- man_hourカラム　命名を考えたほうがいいかも

**Comment by sr-umemura** [comment]
本日打合せにて、下記のように変更となりました

# users
- 権限種別カラム追加

# projects
- プロジェクトID…カラム追加
- 開始日…用途は入力者にゆだねる
- 内部納期…カラム削除
- 窓口担当社員ID…カラム削除

# tasks
- project_usersにテーブル名変更

# man_hours
- tasksにテーブル名変更
- man_hourカラム名はそのまま

# department_users（部署社員管理）
- 新規追加

# roles（役割マスタ）
- 新規追加

# project_user_roles（案件社員役割管理）
- 新規追加

**Comment by maeda-san** [comment]
# Review

前回の内容の再確認お願いします

## users
- 権限カラム→OK!
- **パスワード追加(新規)**

## projects
- **プロジェクトID(サロゲートキーでなく)が必要 NG!**
- **開始日はどのタイミング?(制作の開始日?or見積もり日?or得意先にその案件で初コンタクトをとったとき?)→入力者の用途に委ねるならNULL可かな?**
- 内部納期が必要(Not Null)かどうか(コーディング案件やデザイン案件で内部納期を設定する慣習があるのかよくわからない)→OK!
- 窓口担当社員IDは複数持てるようにしたほうが良いかも→OK!

## project_users
- **開始日・終了日は予定?また、タスク作成時に確定しなさそうな項目。どういった利用用途を想定?→これどうなったっけ?**

## tasks
- man_hourカラム　命名を考えたほうがいいかも→OK!

## department_users

OK!

## roles

OK!

## project_user_roles

OK!

## 日報系

**(新規)**

## Qiita.teamへの投稿

**(実は既存)**

**Comment by sr-umemura** [comment]
# 日報
- dailyreports テーブルを新規作成

# projects
- プロジェクトIDカラムを追加しました
- 開始日→NULL可にしました

# project_users
- 開始日→NULL可にしました

# users
- パスワードカラム追加しました
